name: CI

on:
    pull_request:
        branches: ['master-netlify']
        # branches: ['master', 'stable']
    push:
        branches: ['master-netlify']
        # branches: ['master', 'stable']

jobs:
    clayui:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1

            - name: clayui.com changes
              run: git diff ${{ github.event.pull_request.head.sha }} HEAD clayui.com
            - name: Build clayui.com
              if: ${{ success() }}
              run: echo "run clayui.com"


    storybook:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              
            - name: storybook changes
              run: git diff ${{ github.event.pull_request.head.sha }} HEAD packages
            - name: Build Storybook
              if: ${{ success() }}
              run: echo "run storybook"
