name: CI

on:
    pull_request:
        branches: ['master-netlify']
        # branches: ['master', 'stable']
    push:
        branches: ['master-netlify']
        # branches: ['master', 'stable']

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1

            - name: fetch base
              run: git fetch --no-tags --depth=1 origin ${{ github.base_ref }}

            - name: Storybook
              run: git diff-tree --exit-code -r ${{ github.base_ref }}

            - name: Verify Dependencies
              if: ${{ success() }}
              run: echo "run"
