name: CI

on:
    pull_request:
        branches: ['master-netlify', 'stable-netlify']
        # branches: ['master', 'stable']
    push:
        branches: ['master-netlify', 'stable-netlify']
        # branches: ['master', 'stable']

jobs:
    # test:
    #     runs-on: ubuntu-latest
    #     steps:
    #         - uses: actions/checkout@v2
    #         - uses: actions/setup-node@v1
    #         - name: Install
    #           run: |
    #               npm install -g yarn
    #               yarn install

    #         - name: Formatting
    #           run: |
    #               yarn lint
    #               yarn format:check
    #         - name: Dependencies
    #           run: yarn checkDeps

    #         - name: Jest
    #           env:
    #               CI: true
    #           run: yarn test --coverage

    #         - name: Coveralls
    #           if: ${{ success() }}
    #           uses: coverallsapp/github-action@v1.1.1
    #           with:
    #               path-to-lcov: ./coverage/lcov.info
    #               github-token: ${{ secrets.GITHUB_TOKEN }}

    # stats:
    #     runs-on: ubuntu-latest
    #     steps:
    #         - uses: actions/setup-node@v1

    #         - name: Checkout BASE
    #           uses: actions/checkout@v2
    #           with:
    #               ref: ${{ github.event.pull_request.base.sha }}

    #         - name: Generate Build Info
    #           run: |
    #               yarn install
    #               node ./node_modules/.bin/lerna run --ignore \"clayui.com\" build
    #               yarn genBuildSize

    #         - name: Clean directory
    #           if: ${{ success() }}
    #           run: |
    #               git clean -ffdx --exclude /tmp
    #               git reset --hard HEAD
    #         - name: Checkout HEAD
    #           if: ${{ success() }}
    #           uses: actions/checkout@v2
    #           with:
    #               ref: ${{ github.event.pull_request.head.sha }}
    #               clean: false

    #         - name: Generate Bundle Size Table
    #           if: ${{ success() }}
    #           run: |
    #               yarn install
    #               node ./node_modules/.bin/lerna run --ignore \"clayui.com\" build
    #               yarn genBuildSize:compare
    #         - name: Generate Total Size
    #           if: ${{ success() }}
    #           run: yarn run sizeLimit

    netlify:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
            # - name: Install
            #   run: |
            #       npm install -g yarn
            #       yarn install

            # - name: Fetch and Diff
            #   id: diff
            #   run: |
            #       git fetch --no-tags --depth=1 origin ${{ github.event.pull_request.base.sha }}
            #       echo "##[set-output name=storybook;]$(git diff --exit-code ${{ github.event.pull_request.base.sha }} '**/stories*' '**/src*')"
            #       echo "##[set-output name=clayui;]$(git diff --exit-code ${{ github.event.pull_request.base.sha }} clayui.com '**/*.mdx' '**/docs*')"

            # - name: Build Storybook
            #   if: ${{ steps.diff.outputs.storybook }}
            #   run: |
            #       yarn workspace @clayui/css run build && yarn storybook:build

            # - name: Build clayui
            #   if: ${{ steps.diff.outputs.clayui }}
            #   run: |
            #       cd clayui.com && yarn build

            - name: Check Branch
              id: branch
              run: |
                  echo "::set-output name=storybook::$(${{ github.ref == 'stable' }} ? ${{ secrets.NETLIFY_STORYBOOK_ID }} : ${{ secrets.NETLIFY_NEXT_STORYBOOK_ID }})"
                  echo "::set-output name=clayui::$(${{ github.ref == 'stable' }} ? ${{ secrets.NETLIFY_CLAYUI_ID }} : ${{ secrets.NETLIFY_NEXT_CLAYUI_ID }})"

            - name: Echo?
              run: |
                  echo "${{ github.ref }}: ${{ steps.branch.storybook == 'storybook' }}"
                  echo "${{ github.ref }}: ${{ steps.branch.clayui == 'clayui' }}"
            # - name: Deploy Storybook Preview
            #   if: ${{ steps.diff.outputs.storybook }}
            #   uses: netlify/actions/cli@master
            #   with:
            #       args: deploy --dir=storybook-static
            #   env:
            #       NETLIFY_SITE_ID: ${{ secrets.NETLIFY_NEXT_STORYBOOK_ID }}
            #       NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
            # - name: Deploy clayui.com Preview
            #   if: ${{ steps.diff.outputs.storybook }}
            #   uses: netlify/actions/cli@master
            #   with:
            #       args: deploy --dir=clayui.com/public
            #   env:
            #       NETLIFY_SITE_ID: ${{ secrets.NETLIFY_NEXT_CLAYUI_ID }}
            #       NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
