name: CI

on:
    pull_request:
        branches: ['master-netlify']
        # branches: ['master', 'stable']
    push:
        branches: ['master-netlify']
        # branches: ['master', 'stable']

jobs:
    netlify:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
            - name: Build Storybook
              if: git diff ${{ github.event.pull_request.base.sha }} HEAD clayui.com
              run: yarn storybook:build

            - name: Build clayui.com
              run: cd clayui.com && yarn build
