name: CI

on:
    pull_request:
        branches: ['master-netlify']
        # branches: ['master', 'stable']
    push:
        branches: ['master-netlify']
        # branches: ['master', 'stable']

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1

            - name: fetch base
              run: git fetch --no-tags --depth=1 origin ${{ github.event.pull_request.base.sha }}

            - name: Storybook
              id: storybook-diff
              run: git diff-tree --exit-code -r ${{ github.event.pull_request.base.sha }} packages

            - name: clayui.com
              id: clayui-diff
              run: git diff-tree --exit-code -r ${{ github.event.pull_request.base.sha }} clayui.com

            - name: Build Storybook
              if: ${{ steps.storybook-diff.conclusion == 'success' }}
              run: echo "run"

            - name: Build clayui
              if: ${{ steps.clayui-diff.conclusion == 'success' }}
              run: echo "run"
              
