name: CI

on:
    pull_request:
        branches: ['master-netlify']
        # branches: ['master', 'stable']
    push:
        branches: ['master-netlify']
        # branches: ['master', 'stable']

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 50
            - uses: actions/setup-node@v1

            - name: Check Formatting
              run: git diff-tree --no-commit-id --name-only -r ${{ github.event.pull_request.base.sha }}

            - name: Verify Dependencies
              if: ${{ success() }}
              run: echo "run"
