name: CI

on:
    pull_request:
        branches: ['master']
    push:
        branches: ['master']

jobs:
    run:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
            - name: Install yarn & Dependencies
              run: |
                  npm install -g yarn
                  yarn install
            - name: Check Formatting
              run: |
                  yarn lint
                  yarn format:check
            - name: Verify Dependencies
              run: yarn checkDeps
            - name: Run Jest
              env:
                  CI: true
              run: yarn test --coverage
            - name: Generate Coverage Report
              uses: coverallsapp/github-action@v1.1.1
              with:
                  path-to-lcov: ./coverage/lcov.info
                  github-token: ${{ secrets.GITHUB_TOKEN }}
