name: CI
on:
    pull_request:
        branches: ['master']

jobs:
    run:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-node@v1
            - name: Install yarn
              run: npm install -g yarn
            - name: Checkout BASE
              uses: actions/checkout@v2
            - name: Install Dependencies
              run: yarn install
            - name: Check Formatting
              run: |
                  yarn lint
                  yarn format:check
            - name: Verify Dependencies
              run: yarn checkDeps
            - name: Run Jest
              env:
                  CI: true
              run: yarn test --coverage
            - name: Generate Coverage Report
              uses: coverallsapp/github-action@v1.1.1
              with:
                  path-to-lcov: ./coverage/lcov.info
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  parallel: true
    finish:
        needs: run
        runs-on: ubuntu-latest
        steps:
            - uses: coverallsapp/github-action@v1.1.1
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  parallel-finished: true
