name: Comment Build Stats

on:
    pull_request:
        branches: [master]

jobs:
    build_and_comment:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-node@v1
            - name: Run checkSize.js
              run: |
                  npm install -g yarn
                  yarn install
                  yarn checkSize
            - name: Post comment on PR
              env:
                  URL: ${{ github.event.issue.comments_url }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  curl \
                      -X POST \
                      $URL \
                      -H "Content-Type: application/json" \
                      -H "Authorization: token $GITHUB_TOKEN" \
                      --data @.parcel-ci-build.json
