name: CI

on:
    pull_request:
        branches: ['master']
    push:
        branches: ['master']

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
            - name: Install yarn & Dependencies
              run: |
                  npm install -g yarn
                  yarn install
            - name: Check Formatting
              run: |
                  yarn lint
                  yarn format:check
            - name: Verify Dependencies
              run: yarn checkDeps
            - name: Run Jest
              env:
                  CI: true
              run: yarn test --coverage
            - name: Push to Coveralls
              if: ${{ success() }}
              uses: coverallsapp/github-action@v1.1.1
              with:
                  path-to-lcov: ./coverage/lcov.info
                  github-token: ${{ secrets.GITHUB_TOKEN }}

    stats:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-node@v1
            - name: Checkout BASE
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.event.pull_request.base.sha }}
            - name: Generate Build Info
              run: |
                  yarn install
                  node ./node_modules/.bin/lerna run --ignore \"clayui.com\" build
                  yarn genBuildSize
            - name: Clean directory
              run: |
                  git clean -ffdx --exclude /tmp
                  git reset --hard HEAD
            - name: Checkout HEAD
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.event.pull_request.head.sha }}
                  clean: false
            - name: Generate Bundle Size Table
              run: |
                  yarn install
                  node ./node_modules/.bin/lerna run --ignore \"clayui.com\" build
                  yarn genBuildSize:compare
            - name: Generate Total Size
              run: |
                  yarn run sizeLimit
