name: Comment Build Stats

on:
    pull_request:
        branches: [master]

jobs:
    build_and_comment:
        runs-on: ubuntu-latest
        steps:
            - name: Setup yarn
            - uses: actions/setup-node@v1
            - run: |
                  npm install -g yarn
            - name: Get stats at base
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.event.pull_request.base.sha }}
            - run: |
                  yarn install
                  yarn checkSize
            - name: Get stats at HEAD
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.event.pull_request.head.sha }}
            - run: |
                  yarn install
                  yarn checkSize:compare
            - name: Post comment on PR
              env:
                  URL: ${{ github.event.pull_request.comments_url }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  curl \
                      -X POST \
                      $URL \
                      -H "Content-Type: application/json" \
                      -H "Authorization: token $GITHUB_TOKEN" \
                      --data @.parcel-ci-build.json
