name: Share data between jobs

on:
    pull_request:
        branches: [master]

jobs:
    job_1:
        name: Run Build Stats and Upload
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: '10.x'
            - run: npm install -g yarn
            - run: yarn install
            - run: yarn checkSize
            - name: Comment on PR
              uses: machine-learning-apps/pr-comment@master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  path: .parcel-ci-build.txt
