name: Stats
on:
    pull_request:
        branches: ['master']

jobs:
    run:
        name: Packages
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-node@v1
            - name: Install yarn
              run: |
                  npm install -g yarn
                  yarn global add lerna
            - name: Checkout BASE
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.event.pull_request.base.sha }}
            - name: Generate Build Info
              run: |
                  yarn install
                  lerna run --ignore \"clayui.com\" build
                  yarn genBuildSize
            - name: Clean directory
              run: |
                  git clean -ffdx --exclude /tmp
                  git reset --hard HEAD
            - name: Checkout HEAD
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.event.pull_request.head.sha }}
                  clean: false
            - name: Generate Bundle Size Table
              run: |
                  yarn install
                  lerna run --ignore \"clayui.com\" build
                  yarn genBuildSize:compare
            - name: Generate Total Size
              run: |
                  yarn run bundle
                  yarn run sizeLimit
